---
# ----------------------------------------------------------
# Namespace for Redis
# This ensures all Redis-related objects (deployment, secrets, services, PVCs)
# are grouped into the `redis-system` namespace for isolation and easier management.
# Adaptation: You can change the namespace name, but ensure all resources
# in this file are updated to match if you do so.
# ----------------------------------------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: redis-system
---
# ----------------------------------------------------------
# Secret containing the Redis password
# This stores the Redis authentication password securely in Kubernetes.
# The password is mounted into the Redis container as an environment variable.
# Adaptation: Replace `REDIS_SECRET_KEY_STR` with your own secure password.
# Ensure it matches any client connections.
# ----------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: redis-system
type: Opaque
stringData:
  REDIS_PASSWORD: REDIS_SECRET_KEY_STR
---
# ----------------------------------------------------------
# MetalLB IP Address Pool
# This allocates a single IP (172.16.254.19) from MetalLB to be used by the Redis service.
# Adaptation: Change this IP to one available in your MetalLB address pool range.
# This must be configured to match your cluster’s network environment.
# Prerequisite: MetalLB must already be installed in the `metallb-system` namespace.
# ----------------------------------------------------------
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: redis-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.16.254.19-172.16.254.19
---
# ----------------------------------------------------------
# MetalLB L2Advertisement
# This announces the IP (from the IPAddressPool) to your network via L2 protocols.
# Adaptation: Change `eth0` to the network interface that connects
# your cluster nodes to the external network.
# ----------------------------------------------------------
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: redis-advertisement
  namespace: metallb-system
spec:
  interfaces:
    - eth0
---
# ----------------------------------------------------------
# Redis StatefulSet
# Deploys a single Redis pod with persistent storage and password authentication.
# Uses StatefulSet to ensure stable network identity and persistent storage binding.
# Password is passed to redis-server from a Secret via the REDIS_PASSWORD env var.
# Adaptation:
# - Change the Redis image version if needed.
# - Adjust replicas if you want Redis replication (requires extra config).
# - Ensure nfs-client StorageClass is available.
# ----------------------------------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis-system
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
          env:
            - name: REDIS_PASSWORD
              valueFrom:
               secretKeyRef:
                 name: redis-secret
                 key: REDIS_PASSWORD
          args: ["--save", "", "--appendonly", "yes", "--requirepass", "$(REDIS_PASSWORD)"]
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: nfs-client
        resources:
          requests:
            storage: 1Gi
---
# ----------------------------------------------------------
# Redis Service (LoadBalancer)
# Exposes Redis on port 6379 via a LoadBalancer IP from MetalLB.
# Clients inside or outside the cluster can connect using this IP.
# Adaptation: Ensure `loadBalancerIP` matches an address in your MetalLB pool.
# ----------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis-system
spec:
  selector:
    app: redis
  type: LoadBalancer
  loadBalancerIP: 172.16.254.19
  ports:
    - port: 6379
      targetPort: 6379
