# AUTOGENERATED: DO NOT EDIT MANUALLY
module CustomAppVersions

  def self.rstudio_server_module_list
    [
      ["RStudio Server 4.3", "rstudio-server/4.3"],
      ["RStudio Server 4.4", "rstudio-server/4.4"],
    ].reverse
  end

  def self.code_server_module_list
    [
      ["VS Code Server 4.92.2", "code-server/4.92.2"],
      ["VS Code Server 4.101.2", "code-server/4.101.2"],
    ].reverse
  end

  def self.paraview_module_list
    [
      ["ParaView 5.11.2", "paraview/5.11.2"],
      ["ParaView 5.13.1", "paraview/5.13.1"],
    ].reverse
  end

  def self.qgis_module_list
    [
      ["QGIS 3.28.12", "qgis/3.28.12"],
    ].reverse
  end

  def self.blender_module_list
    [
      ["Blender 4.0.2", "blender/4.0.2"],
      ["Blender 4.2.8", "blender/4.2.8"],
    ].reverse
  end

  def self.octave_module_list
    [
      ["Octave 7.2.0", "octave/7.2.0"],
    ].reverse
  end

  def self.mujoco_module_list
    [
      ["MuJoCo 3.0.1", "mujoco/3.0.1"],
      ["MuJoCo 3.0.1", "mujoco/3.0.1"],
      ["MuJoCo 3.1.6", "mujoco/3.1.6"],
      ["MuJoCo 3.1.6", "mujoco/3.1.6"],
      ["MuJoCo 3.3.0", "mujoco/3.3.0"],
      ["MuJoCo 3.3.0", "mujoco/3.3.0"],
    ].reverse
  end

  def self.afni_module_list
    [
      ["afni 24.1.03", "afni/24.1.03"],
    ].reverse
  end

  def self.gnuplot_module_list
    [
      ["gnuplot 5.4.8", "gnuplot/5.4.8"],
    ].reverse
  end

  def self.geant4_module_list
    [
      ["geant4 11.1.2", "geant4/11.1.2"],
      ["geant4 11.2.1", "geant4/11.2.1"],
      ["geant4 11.3.0", "geant4/11.3.0"],
    ].reverse
  end

  def self.visit_module_list
    [
    ].reverse
  end

  def self.matlab_module_list
    [
      ["matlab 2023b.2", "matlab/2023b.2"],
      ["matlab 2024b.1", "matlab/2024b.1"],
    ].reverse
  end

  def self.vmd_module_list
    [
      ["VMD 1.9.4a57", "vmd/1.9.4a57"],
    ].reverse
  end
end
