# AUTOGENERATED: DO NOT EDIT MANUALLY
# softmig_slices=4 effective_tier=4 gres_has_shard=1
module CustomGPUInfo
  def self.gpu_types
    [
      "l40s",
      "l40s.2",
      "l40s.4",
    ]
  end
  def self.gpu_name_mappings
    {
      "l40s" => "NVIDIA L40S (full)",
      "l40s.2" => "NVIDIA L40S (1/2 GPU)",
      "l40s.4" => "NVIDIA L40S (1/4 GPU)",
    }
  end
  def self.gpu_max_counts
    {
      "l40s" => 4,
      "l40s.2" => 8,
      "l40s.4" => 16,
    }
  end
  def self.gpu_sharing_available
    true
  end
  def self.slices_per_gpu
    4
  end
end
