# AUTOGENERATED: DO NOT EDIT MANUALLY
module CustomGPUInfo
  def self.gpu_types
    [
      "l40s",
    ]
  end
  def self.gpu_name_mappings
    {
      "l40s" => "NVIDIA L40S",
    }
  end
  def self.gpu_max_counts
    {
      "l40s" => 4,
    }
  end
end
