# AUTOGENERATED: DO NOT EDIT MANUALLY
module CustomClusterInfo
  def self.cluster_name
    "vulcan"
  end
  def self.partitions
    [
      "cpubase_interac",
      "cpubase_short",
      "gpubase_bygpu_b1",
      "gpubase_bygpu_b2",
      "gpubase_bygpu_b3",
      "gpubase_bygpu_b4",
      "gpubase_bygpu_b5",
      "gpubase_bynode_b1",
      "gpubase_bynode_b2",
      "gpubase_bynode_b3",
      "gpubase_bynode_b4",
      "gpubase_bynode_b5",
      "gpubase_interac",
    ]
  end
  def self.max_cpus_per_node
    128
  end
  def self.max_memory_per_node
    504
  end
end
