#!/bin/bash
set -euo pipefail

OUTDIR="/etc/ood/config/apps/dashboard/initializers"
OUTFILE="${OUTDIR}/paice_cluster_info.rb"

mkdir -p "$OUTDIR"

echo "# AUTOGENERATED: DO NOT EDIT MANUALLY" > "$OUTFILE"
echo "module CustomClusterInfo" >> "$OUTFILE"

# Cluster name
CLUSTER_NAME=$(scontrol show config | awk -F= '/ClusterName/ {gsub(/^[ \t]+/, "", $2); print $2}')
CLUSTER_NAME=${CLUSTER_NAME:-unknown}
echo "  def self.cluster_name" >> "$OUTFILE"
echo "    \"$CLUSTER_NAME\"" >> "$OUTFILE"
echo "  end" >> "$OUTFILE"

# Unique partitions
echo "  def self.partitions" >> "$OUTFILE"
echo "    [" >> "$OUTFILE"
scontrol show partition | awk -F= '/PartitionName=/{print $2}' | sort -u | while read -r part; do
  echo "      \"$part\"," >> "$OUTFILE"
done
echo "    ]" >> "$OUTFILE"
echo "  end" >> "$OUTFILE"

# Max CPUs per node
echo "  def self.max_cpus_per_node" >> "$OUTFILE"
MAX_CPUS=$(scontrol show node | grep -oP 'CPUTot=\K\d+' | sort -nr | head -n1)
MAX_CPUS=${MAX_CPUS:-64}
echo "    $MAX_CPUS" >> "$OUTFILE"
echo "  end" >> "$OUTFILE"

# Max memory per node (in GB)
echo "  def self.max_memory_per_node" >> "$OUTFILE"
MAX_MEM_MB=$(scontrol show node | grep -oP 'RealMemory=\K\d+' | sort -nr | head -n1)
MAX_MEM_GB=$(( (MAX_MEM_MB + 1023) / 1024 ))
MAX_MEM_GB=${MAX_MEM_GB:-128}
echo "    $MAX_MEM_GB" >> "$OUTFILE"
echo "  end" >> "$OUTFILE"

echo "end" >> "$OUTFILE"

chmod 644 "$OUTFILE"
echo "Generated $OUTFILE successfully at $(date)"

