#!/bin/bash
set -euo pipefail

OUTDIR="/etc/ood/config/apps/dashboard/initializers"
OUTFILE="${OUTDIR}/paice_gpu_info.rb"

mkdir -p "$OUTDIR"

# Run the command once
gpu_output=$(scontrol show node | grep -oP 'Gres=\K[^ ]+' | sort | uniq)

echo "# AUTOGENERATED: DO NOT EDIT MANUALLY" > "$OUTFILE"
echo "module CustomGPUInfo" >> "$OUTFILE"

# gpu_types
echo "  def self.gpu_types" >> "$OUTFILE"
echo "    [" >> "$OUTFILE"
echo "$gpu_output" | grep -oP '^gpu:\K[^:]+' | sort -u | while read -r gpu; do
    [[ -n "$gpu" ]] && echo "      \"$gpu\"," >> "$OUTFILE"
done
echo "    ]" >> "$OUTFILE"
echo "  end" >> "$OUTFILE"

# gpu_name_mappings
echo "  def self.gpu_name_mappings" >> "$OUTFILE"
echo "    {" >> "$OUTFILE"
echo "$gpu_output" | grep -oP '^gpu:\K[^:]+' | sort -u | while read -r gpu; do
    [[ -n "$gpu" ]] && echo "      \"$gpu\" => \"NVIDIA ${gpu^^}\"," >> "$OUTFILE"
done
echo "    }" >> "$OUTFILE"
echo "  end" >> "$OUTFILE"

# gpu_max_counts
echo "  def self.gpu_max_counts" >> "$OUTFILE"
echo "    {" >> "$OUTFILE"
echo "$gpu_output" | grep '^gpu:' | while read -r line; do
    gpu=$(echo "$line" | cut -d':' -f2)
    count=$(echo "$line" | cut -d':' -f3)
    [[ -n "$gpu" && -n "$count" ]] && echo "      \"$gpu\" => $count," >> "$OUTFILE"
done
echo "    }" >> "$OUTFILE"
echo "  end" >> "$OUTFILE"

echo "end" >> "$OUTFILE"


chmod 644 "$OUTFILE"
echo "Generated $OUTFILE successfully at $(date)"

